# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'ArmoireApp' do

pod 'LayerKit'
pod 'Atlas'
pod 'Parse'
pod 'ParseUI'
pod 'MZFormSheetPresentationController'
pod 'SDWebImage'

end

